import 'package:tapster/models/tapster_config.dart';
import 'package:tapster/services/asset_service.dart';

class FormulaService {
  static const String defaultFormulaTemplate = '''
# Generated by tapster on {{TIMESTAMP}}
class {{CLASS_NAME}} < Formula
  desc "{{DESCRIPTION}}"
  homepage "{{HOMEPAGE}}"
{{#if LINUX_URL}}  if OS.mac?
    url "{{URL}}"
    sha256 "{{SHA256}}"
  else
    url "{{LINUX_URL}}"
    sha256 "{{LINUX_SHA256}}"
  end
{{else}}  url "{{URL}}"
  sha256 "{{SHA256}}"
{{/if}}
  license "{{LICENSE}}"

  {{#each depends_on_brew}}depends_on "{{this}}"{{/each}}

  def install
{{#if LINUX_URL}}    if OS.mac?
      {{MAC_INSTALL}}
    else
      {{LINUX_INSTALL}}
    end
{{else}}    {{INSTALL}}
{{/if}}
  end

  test do
    system {{TEST_CMD}}, "--version"
  end
end
''';

  /// 生成 Formula。`linuxChecksum` 非空时（对应 `formulaConfig.linuxAsset`）
  /// 输出 macOS/Linux 双平台条件块，否则只有 macOS 单 url。
  Future<String> generateFormula(
    TapsterConfig config,
    FormulaConfig formulaConfig, {
    required String version,
    String? linuxChecksum,
  }) async {
    final assetService = AssetService();
    final now = DateTime.now().toUtc();
    final timestamp = now.toIso8601String();

    final Map<String, dynamic> context = {
      'CLASS_NAME': _toClassName(config.name),
      'DESCRIPTION': config.description,
      'HOMEPAGE': config.homepage,
      'LICENSE': config.license,
      'TIMESTAMP': timestamp,
    };

    // Handle asset
    if (formulaConfig.asset.isNotEmpty) {
      context['URL'] = _getDefaultUrl(config, version, formulaConfig.asset);
      // 预置 checksum 时不读取本地 asset（跨平台发布时 asset 可能不在本地）
      context['SHA256'] = formulaConfig.checksum ??
          (await assetService.getAssetInfo(formulaConfig.asset)).checksum;
      final macExecutable = AssetService.basename(formulaConfig.asset);
      context['INSTALL'] = _installStatement(macExecutable, config.name);
      context['MAC_INSTALL'] = context['INSTALL'];
      // 安装后命令名 = 包名（rename 或同名皆然）
      context['TEST_CMD'] = '"#{bin}/${config.name}"';
    }

    // Optional Linux asset — dual-platform formula
    final linuxAsset = formulaConfig.linuxAsset;
    if (linuxAsset != null && linuxAsset.isNotEmpty) {
      context['LINUX_URL'] = _getDefaultUrl(config, version, linuxAsset);
      context['LINUX_SHA256'] = linuxChecksum ??
          (await assetService.getAssetInfo(linuxAsset)).checksum;
      context['LINUX_INSTALL'] = _installStatement(
        AssetService.basename(linuxAsset),
        config.name,
      );
    }

    // Handle dependencies
    if (formulaConfig.dependencies.isNotEmpty) {
      context['depends_on_brew'] = formulaConfig.dependencies;
    }

    return _renderTemplate(defaultFormulaTemplate, context);
  }

  /// 安装语句：可执行名与包名一致时不带 rename hash
  /// （`bin.install "tapster"`），不一致时重命名为包名
  /// （`bin.install "tapster-macos" => "tapster"`）。
  String _installStatement(String executable, String installedName) {
    if (executable == installedName) {
      return 'bin.install "$executable"';
    }
    return 'bin.install "$executable" => "$installedName"';
  }

  String _renderTemplate(String template, Map<String, dynamic> context) {
    var result = template;

    // Replace simple variables
    context.forEach((key, value) {
      final placeholder = '{{$key}}';
      result = result.replaceAll(placeholder, value.toString());
    });

    // Handle conditional blocks
    result = _processConditionBlocks(result, context);

    return result;
  }

  String _processConditionBlocks(
    String template,
    Map<String, dynamic> context,
  ) {
    // Handle each loops
    final eachRegex = RegExp(
      r'\{\{#each (\w+)\}\}(.*?)\{\{/each\}\}',
      dotAll: true,
    );
    template = template.replaceAllMapped(eachRegex, (match) {
      final arrayName = match.group(1)!;
      final content = match.group(2)!;
      final array = context[arrayName];

      if (array is List) {
        return array
            .map((item) => content.replaceAll('{{this}}', item.toString()))
            .join('');
      }
      return '';
    });

    // Handle if/else blocks
    final ifElseRegex = RegExp(
      r'\{\{#if (\w+)\}\}(.*?)\{\{else\}\}(.*?)\{\{/if\}\}',
      dotAll: true,
    );
    template = template.replaceAllMapped(ifElseRegex, (match) {
      final condition = match.group(1)!;
      final ifContent = match.group(2)!;
      final elseContent = match.group(3)!;
      final value = context[condition];
      final hasCondition =
          value == true ||
          (value is List && value.isNotEmpty) ||
          value?.toString().isNotEmpty == true;

      return hasCondition ? ifContent : elseContent;
    });

    // Handle simple if blocks
    final ifRegex = RegExp(r'\{\{#if (\w+)\}\}(.*?)\{\{/if\}\}', dotAll: true);
    template = template.replaceAllMapped(ifRegex, (match) {
      final condition = match.group(1)!;
      final content = match.group(2)!;
      final value = context[condition];
      final hasCondition =
          value == true ||
          (value is List && value.isNotEmpty) ||
          value?.toString().isNotEmpty == true;

      return hasCondition ? content : '';
    });

    return template;
  }

  String _toClassName(String packageName) {
    // Convert package name to Ruby class name format
    final parts = packageName.split(RegExp(r'[-_\s]+'));
    return parts
        .map(
          (part) => part.isNotEmpty
              ? '${part[0].toUpperCase()}${part.substring(1)}'
              : '',
        )
        .join('');
  }

  String _getDefaultUrl(TapsterConfig config, String version, String assetPath) {
    // Generate GitHub release URL（asset 文件名，与 cask/scoop 一致；
    // checksum 解析同样按 asset 文件名匹配远端 digest）
    final repo = config.repository.replaceAll('.git', '');
    final assetFileName = AssetService.basename(assetPath);
    return '$repo/releases/download/v$version/$assetFileName';
  }
}
